eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8500/eureka/
server:
  port: 5000
spring:
  application:
    name: gateway-service
zuul:
  host:
    connect-timeout-millis: 60000
  routes:
    api-a:
      path: /api-a/**
      serviceId: user-consumer
    api-b:
      path: /api-b/**
      serviceId: goods-consumer
      add-host-header: true

