server:
  port: 8896
spring:
  application:
    name: goods-consumer
  resources:
    static-locations: classpath:/static/
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8500/eureka/
    instance:
      hostname: localhost
feign:
  hystrix:
    enabled: true
thymeleaf:
  cache: false #关闭默认缓存
  prefix: classpath:/template/
  suffix: .html
  encoding: UTF-8

